workdir: "/path/to/saiq-forge"
datadir: "/path/to/data"
logsdir: "/path/to/outputs/logs"
input:
  file_data: "data/my_parquet_file.parquet"
  file_geo: "data/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ISP-DOMAIN.parquet"
output:
  file_baseline: "data/baseline_stats_for_my_parquet_file.json" # for per-file data profiling
  dir_reports: "data/generated-outputs/reports_from_my_parquet_file"
  dir_tensorboard: "outputs/runs/my_parquet_specific_run/"
nn:
  type: "autoencoder"
  batch_size: 256
  epochs: 5
  learning_rate: 0.001
  autoencoder:
    encoder_hidden_dims: [32, 16] 
    latent_dim: 8                 
  features:
    # --- Original Data (Scaled safely) ---
    use_raw_duration: true
    use_raw_src_bytes: true
    use_raw_dst_bytes: true
    use_raw_src_packets: true
    use_raw_dst_packets: true
    # --- Computed / Robust Data ---
    use_robust_duration: true
    use_robust_src_bytes: true
    use_robust_dst_bytes: true
    use_rare_src_ip: true
    use_protocol_encoding: true