import json
import math
import pyarrow.parquet as pq
import pyarrow.compute as pc

from core.config import load_config

def calculate_entropy(array):
    """
    Calculates the system-wide Shannon Entropy of a categorical/discrete column.
    Formula: H(X) = -sum(P(x_i) * log2(P(x_i)))
    """
    vc = pc.value_counts(array)
    # PyArrow's value_counts returns a StructArray with 'values' and 'counts' fields
    counts = vc.field("counts").to_pylist()
    total = sum(counts)
    if total == 0:
        return 0.0
    
    entropy = 0.0
    for c in counts:
        p = c / total
        if p > 0:
            entropy -= p * math.log2(p)
    return entropy

def generate_baseline(parquet_path, output_json_path):
    print("Opening parquet file and parsing schema...")
    dataset = pq.ParquetDataset(parquet_path)
    
    # Define exact columns to load matching your schema format
    columns = [
        "DURATION", "SRC IP", "DST IP", "SRC PORT", "DST PORT", 
        "PROTOCOL", "APPLICATION", "SRC PACKETS", "DST PACKETS", 
        "SRC BYTES", "DST BYTES", "TIME"
    ]
    table = dataset.read(columns=columns)
    
    stats = {}

    # --- 1. HEAVY-TAILED NUMERICAL PROFILING ---
    print("Profiling numerical distributions via robust quantiles...")
    numerical_cols = ["DURATION", "SRC PACKETS", "DST PACKETS", "SRC BYTES", "DST BYTES"]
    stats["numerical_profiles"] = {}
    
    for col in numerical_cols:
        arr = table[col]
        # Pull diverse quantiles to map out heavy tails cleanly
        q_vals = pc.quantile(arr, q=[0.25, 0.50, 0.75, 0.95, 0.99, 0.999]).to_pylist()
        iqr = q_vals[2] - q_vals[0]
        
        stats["numerical_profiles"][col] = {
            "min": float(pc.min(arr).as_py()),
            "max": float(pc.max(arr).as_py()),
            "mean": float(pc.mean(arr).as_py()),
            "stddev": float(pc.stddev(arr).as_py()),
            "p25": q_vals[0],
            "median": q_vals[1],  # Robust central tendency
            "p75": q_vals[2],
            "p95": q_vals[3],     # Soft threshold for outliers
            "p99": q_vals[4],     # Hard threshold for outliers
            "p999": q_vals[5],    # Extreme value marker
            "iqr": iqr
        }

    # --- 2. STRUCTURAL RATIO PROFILES ---
    print("Computing behavioral asymmetry metrics...")
    # Safe element-wise division by adding 1 packet/byte to denominators
    ratio_src_dst_bytes = pc.divide(table["SRC BYTES"], pc.add(table["DST BYTES"], 1))
    ratio_src_pkt_size = pc.divide(table["SRC BYTES"], pc.add(table["SRC PACKETS"], 1))
    
    stats["ratio_profiles"] = {
        "SRC_TO_DST_BYTES_ASYMMETRY": {
            "median": pc.quantile(ratio_src_dst_bytes, q=0.5)[0].as_py(),
            "p95": pc.quantile(ratio_src_dst_bytes, q=0.95)[0].as_py(),
            "p99": pc.quantile(ratio_src_dst_bytes, q=0.99)[0].as_py()
        },
        "SRC_AVG_PACKET_SIZE": {
            "median": pc.quantile(ratio_src_pkt_size, q=0.5)[0].as_py(),
            "p95": pc.quantile(ratio_src_pkt_size, q=0.95)[0].as_py(),
            "p99": pc.quantile(ratio_src_pkt_size, q=0.99)[0].as_py()
        }
    }

    # --- 3. GLOBAL INFORMATION ENTROPY ---
    print("Calculating system-wide feature entropies...")
    categorical_entropy_cols = ["SRC PORT", "DST PORT", "PROTOCOL", "APPLICATION"]
    stats["global_entropy"] = {}
    for col in categorical_entropy_cols:
        stats["global_entropy"][col] = calculate_entropy(table[col])

    # --- 4. TOPOLOGICAL GRAPH STRUCTURAL PROFILE (Fan-Out) ---
    print("Profiling network structural connection boundaries...")
    # Aggregating to find the count of distinct endpoints each internal source talks to
    grouped_graph = table.group_by("SRC IP").aggregate([
        ("DST IP", "count_distinct"),
        ("DST PORT", "count_distinct")
    ])
    
    # Defensive lookup of column names dynamically generated by PyArrow
    dst_ip_agg_col = [c for c in grouped_graph.column_names if "DST IP" in c][0]
    dst_port_agg_col = [c for c in grouped_graph.column_names if "DST PORT" in c][0]
    
    stats["structural_limits"] = {
        "max_unique_dst_ips_per_src": int(pc.max(grouped_graph[dst_ip_agg_col]).as_py()),
        "p95_unique_dst_ips_per_src": float(pc.quantile(grouped_graph[dst_ip_agg_col], q=0.95)[0].as_py()),
        "max_unique_dst_ports_per_src": int(pc.max(grouped_graph[dst_port_agg_col]).as_py()),
        "p95_unique_dst_ports_per_src": float(pc.quantile(grouped_graph[dst_port_agg_col], q=0.95)[0].as_py())
    }

    # --- 5. CATEGORICAL EXCEPTIONS & CO-OCCURRENCE MAPS ---
    print("Mapping context rules and structural rarities...")
    
    # Rare IPs (Appearing under 3 times total across baseline)
    src_ip_vc = pc.value_counts(table["SRC IP"])
    rare_src_ips = [item["values"] for item in src_ip_vc.to_pylist() if item["counts"] < 3]
    
    dst_ip_vc = pc.value_counts(table["DST IP"])
    rare_dst_ips = [item["values"] for item in dst_ip_vc.to_pylist() if item["counts"] < 3]
    
    stats["categorical_baselines"] = {
        "rare_src_ips_sample": rare_src_ips[:2000],  # Capped limit to control JSON size
        "rare_dst_ips_sample": rare_dst_ips[:2000]
    }
    
    # Map Port-to-Application mappings to discover application masquerading downstream
    port_app_group = table.group_by(["DST PORT", "APPLICATION"]).aggregate([("TIME", "count")])
    count_col = [c for c in port_app_group.column_names if "TIME" in c or "count" in c][0]
    
    port_mapping = {}
    for row in port_app_group.to_pylist():
        port = str(row["DST PORT"])
        app = row["APPLICATION"]
        count = row[count_col]
        
        if count > 5:  # Filter out anomalies to find strong baseline correlations
            if port not in port_mapping:
                port_mapping[port] = []
            if app not in port_mapping[port]:
                port_mapping[port].append(app)
                
    stats["categorical_baselines"]["established_port_applications"] = port_mapping

    # --- 6. EXPORT ARTIFACT ---
    print(f"Writing comprehensive metrics to {output_json_path}...")
    with open(output_json_path, "w") as f:
        json.dump(stats, f, indent=4)
    print("Baseline generation completed successfully!")

if __name__ == "__main__":
    cfg = load_config("config/default.yml")
    generate_baseline(cfg["input"]["file_data"], cfg["output"]["file_baseline"])